### ISSUE TITLE
Some music does not have ID3 Tag

### ISSUE THREAD

**Issue by yifeng361** [mbinary/netease-music-cracker#11]
Line 99: I think setID3 can be revised to the form of "try ... except" as some songs have no ID3 tag present.

**Comment by Leo-Mu** [comment]
是的，这是一个大问题。我现在就是一首歌都出不来，第一首歌就给我报错。

```
[+] Saved in: /home/leo/netease-music-cracker/网易云音乐缓存
        title : Desert Soul
        artist: Yanni
        album : Sensuous Chill
[1]  Yanni - Desert Soul
Traceback (most recent call last):
  File "decrypt.py", line 163, in <module>
    handler.getMusic()
  File "decrypt.py", line 145, in getMusic
    name = self.decrypt(rawname)
  File "decrypt.py", line 99, in decrypt
    self.setID3(info, path)
  File "decrypt.py", line 117, in setID3
    tags = ID3(path)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/id3/_file.py", line 77, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/id3/_tags.py", line 177, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/_util.py", line 533, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/_tags.py", line 111, in __init__
    self.load(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/id3/_file.py", line 154, in load
    self._header = ID3Header(fileobj)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/home/leo/.local/lib/python3.6/site-packages/mutagen/id3/_tags.py", line 66, in __init__
    raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
mutagen.id3._util.ID3NoHeaderError: '/home/leo/netease-music-cracker/网易云音乐缓存/Two Steps From Hell - Breathe.mp3' doesn't start with an ID3 tag
```

而我并不会 python ，看了半天也没看出来应该删除什么部分。同时我也不知道这个程序的读取顺序是什么，删除了输入文件夹按照文件名排序的第一个文件后错误一模一样。

**Comment by heqin-zhu** [comment]
Sorry for replying to you so late. This bug has been fixed. Feel free to ask me if there is any new issue.
